### ISSUE TITLE
Practica de animación

### ISSUE THREAD

**Issue by Nancy2050** [SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-equipo-nancy-brenda-belem#1]
[Practica 4_ Animacion de objetos 3D.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-equipo-nancy-brenda-belem/files/8346423/Practica.4_.Animacion.de.objetos.3D.pdf)

**Comment by dulce-blm** [comment]
[Practica 4_ Animacion de objetos 3D.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-equipo-nancy-brenda-belem/files/8346420/Practica.4_.Animacion.de.objetos.3D.pdf)

**Comment by Anthony4523** [comment]
Calificación: 20 puntos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
